class Events:
    GAME_STARTED = "game_started"
    PLAYER_COLLIDE = "player_collide"
    PLAYER_DAMAGED = "player_damaged"
    PLAYER_DIED = "player_died"
    RUN_RESET = "run_reset"
    PHASE_CHANGED = "phase_changed"
    PHASE_COMPLETED = "phase_completed"
    WAVE_STARTED = "wave_started"
    WAVE_COMPLETED = "wave_completed"
    GAME_COMPLETED = "game_completed"
    BOSS_STARTED = "boss_started"
    BOSS_DAMAGED = "boss_damaged"
    BOSS_DEFEATED = "boss_defeated"
