
ASSETS_PATH = "assets/"
ENEMYS_PATH = ASSETS_PATH + "enemys/"
SCENERY_PATH = ASSETS_PATH + "scenery/"
UI_PATH = ASSETS_PATH + "ui/"
SFX_PATH = ASSETS_PATH + "sfx/"
PATTERNS_PATH = ASSETS_PATH + "patterns/"
PLAYER_IMG_PATH = ASSETS_PATH + "player/foguete-chamas.png"

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080